import { useEffect, useRef, useState } from 'react'
import type * as React from 'react'
import { toast } from 'sonner'
import type { ExtensionInfo, FilingRule, LineIssue, Settings as SettingsShape, ThemeInfo } from '@/lib/types'
import { api } from '@/lib/api'
import { countFilterLines, ignoredLineSummary, lineCountLabel, lineSelectionRange } from '@/lib/userFilters'
import { useAppStore } from '@/lib/store'
import { AppIcon } from '@/components/Icons'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

type Section = 'General' | 'Privacy' | 'Filing' | 'Appearance' | 'Extensions' | 'Shortcuts' | 'About'
const sections: { id: Section; icon: string }[] = [{ id: 'General', icon: 'Settings' }, { id: 'Privacy', icon: 'Shield' }, { id: 'Filing', icon: 'Folder' }, { id: 'Appearance', icon: 'Sun' }, { id: 'Extensions', icon: 'Zap' }, { id: 'Shortcuts', icon: 'Command' }, { id: 'About', icon: 'CircleHelp' }]
const shortcuts = [['New tab', 'Ctrl+T'], ['Close tab', 'Ctrl+W'], ['Focus address bar', 'Ctrl+L'], ['Command palette', 'Ctrl+K'], ['Next tab', 'Ctrl+Tab'], ['Toggle sidebar', 'Ctrl+B'], ['Split with next tab', 'Ctrl+\\'], ['Developer panel', 'Ctrl+Shift+D'], ['Open devtools', 'F12']]

export default function SettingsPage() {
  const snapshot = useAppStore((state) => state.snapshot)
  const adblock = useAppStore((state) => state.adblock)
  const [section, setSection] = useState<Section>('General')
  const [themes, setThemes] = useState<ThemeInfo[]>([])
  const [extensions, setExtensions] = useState<ExtensionInfo[]>([])
  const [rules, setRules] = useState<FilingRule[]>(snapshot?.filingRules ?? [])
  const [customSearch, setCustomSearch] = useState('')
  const settings = snapshot?.settings
  useEffect(() => { void api.listThemes().then(setThemes); void api.listExtensions().then(setExtensions); void api.getAdblockStatus().then(useAppStore.getState().setAdblock) }, [])
  useEffect(() => { if (snapshot) setRules(snapshot.filingRules) }, [snapshot?.filingRules])
  if (!settings) return <div className="page-scroll"><p>Settings are not available yet.</p></div>
  const patch = (values: Partial<SettingsShape>) => void api.setSettings(values)
  const persistRules = (next: FilingRule[]) => { setRules(next); void api.setFilingRules(next) }
  const install = async () => { const path = await api.pickDirectory(); if (path) { await api.installExtension(path); setExtensions(await api.listExtensions()) } }
  return <div className="settings-layout" data-part="settings">
    <nav className="settings-nav" aria-label="Settings sections">{sections.map((item) => <button key={item.id} className="settings-nav-item" data-active={String(section === item.id)} onClick={() => setSection(item.id)}><AppIcon name={item.icon} />{item.id}</button>)}</nav>
    <div className="settings-scroll page-scroll"><header className="page-header"><div><span className="placeholder-eyebrow">Athanor preferences</span><h1>{section}</h1><p className="muted-copy">Tune how your workspace feels and behaves.</p></div></header>
      {section === 'General' && <>
        <section className="page-section"><h2>Search and startup</h2><div className="settings-grid"><label htmlFor="search-engine">Search engine</label><select id="search-engine" className="select" value={['https://www.google.com/search?q={q}', 'https://duckduckgo.com/?q={q}', 'https://www.bing.com/search?q={q}'].includes(settings.searchEngine) ? settings.searchEngine : 'custom'} onChange={(event) => { if (event.target.value !== 'custom') patch({ searchEngine: event.target.value }); else if (customSearch) patch({ searchEngine: customSearch }) }}><option value="https://www.google.com/search?q={q}">Google</option><option value="https://duckduckgo.com/?q={q}">DuckDuckGo</option><option value="https://www.bing.com/search?q={q}">Bing</option><option value="custom">Custom template</option></select></div><div className="settings-grid"><label htmlFor="custom-search">Custom URL template <span className="muted-copy">Use {'{q}'} for your query</span></label><Input id="custom-search" value={customSearch || (!['https://www.google.com/search?q={q}', 'https://duckduckgo.com/?q={q}', 'https://www.bing.com/search?q={q}'].includes(settings.searchEngine) ? settings.searchEngine : '')} placeholder="https://example.com/search?q={q}" onChange={(event) => setCustomSearch(event.target.value)} onBlur={() => { if (customSearch.includes('{q}')) patch({ searchEngine: customSearch }) }} /></div><SwitchRow label="Restore previous session" description="Bring back your open tabs when Athanor starts." checked={settings.restoreSession} onChange={(restoreSession) => patch({ restoreSession })} /><div className="settings-grid"><label htmlFor="archive-hours">Archive inactive tabs after</label><div className="range-field"><input id="archive-hours" type="range" min="0" max="168" step="1" value={settings.archiveAfterHours} onChange={(event) => patch({ archiveAfterHours: Number(event.target.value) })} /><span>{settings.archiveAfterHours === 0 ? 'Never' : `${settings.archiveAfterHours} hours`}</span></div></div></section>
        <section className="page-section"><h2>Sidebar</h2><div className="settings-grid"><label htmlFor="sidebar-side">Position</label><select id="sidebar-side" className="select" value={settings.sidebarSide} onChange={(event) => patch({ sidebarSide: event.target.value as 'left' | 'right' })}><option value="left">Left</option><option value="right">Right</option></select></div><SwitchRow label="Compact sidebar" description="Show a smaller icon rail." checked={settings.sidebarCompact} onChange={(sidebarCompact) => patch({ sidebarCompact })} /><div className="settings-grid"><label htmlFor="sidebar-width">Sidebar width</label><div className="range-field"><input id="sidebar-width" type="range" min="208" max="400" value={settings.sidebarWidth} onChange={(event) => patch({ sidebarWidth: Number(event.target.value) })} /><span>{settings.sidebarWidth}px</span></div></div></section>
      </>}
      {section === 'Privacy' && <>
        <section className="page-section"><h2>Ad and tracker blocking</h2><SwitchRow label="Built-in adblock" description="Block requests with local filter lists." checked={adblock?.enabled ?? settings.adblockEnabled} onChange={(enabled) => void api.setAdblockEnabled(enabled)} /><div className="list-heading"><span>Filter lists</span><Button size="sm" variant="outline" disabled={adblock?.updating} onClick={() => void api.updateAdblockLists()}><AppIcon name="RotateCw" />{adblock?.updating ? 'Updating…' : 'Update now'}</Button></div>{adblock?.lists.map((list) => <div className="filter-row" key={list.id}><div><strong>{list.name}</strong><span className="muted-copy">{list.ruleCount.toLocaleString()} rules · {list.updatedAt ? `Updated ${new Date(list.updatedAt).toLocaleDateString()}` : 'Not updated'}{list.error ? ` · ${list.error}` : ''}</span></div><Switch checked={list.enabled} label={`${list.name} list`} onChange={(enabled) => void api.setAdblockListEnabled(list.id, enabled)} /></div>)}</section>
        <section className="page-section"><h2>My filters</h2><MyFiltersEditor /></section>
        <section className="page-section"><h2>Protection preferences</h2><SwitchRow label="Upgrade to HTTPS" description="Prefer encrypted connections when available." checked={settings.httpsUpgrade} onChange={(httpsUpgrade) => patch({ httpsUpgrade })} /><SwitchRow label="Strip tracking parameters" description="Remove common tracking keys from addresses." checked={settings.stripTracking} onChange={(stripTracking) => patch({ stripTracking })} /><p className="muted-copy">{snapshot?.blockedTotal.toLocaleString()} requests blocked across this session.</p></section>
      </>}
      {section === 'Filing' && <>
        <section className="page-section"><div className="section-title-row"><div><h2>Automatic filing</h2><p>Group tabs into named folders using a matching site, URL path, or title.</p></div><Button variant="outline" onClick={() => void api.autoFileAll()}><AppIcon name="WandSparkles" />Run now</Button></div><SwitchRow label="File new tabs automatically" description="Use these rules when a tab opens." checked={settings.autoFile} onChange={(autoFile) => patch({ autoFile })} /></section>
        <section className="page-section"><div className="list-heading"><h2>Filing rules</h2><Button size="sm" onClick={() => persistRules([...rules, { id: crypto.randomUUID(), folder: '', host: '', pathPrefix: null, titleContains: null, enabled: true }])}><AppIcon name="Plus" />Add rule</Button></div><p>Built-in destinations include Development, Reading list, Shopping, Social, and Design. Rules create a folder the first time a match appears.</p>{rules.map((rule) => <div className="rule-editor" key={rule.id}><Switch checked={rule.enabled} label="Enable rule" onChange={(enabled) => persistRules(rules.map((item) => item.id === rule.id ? { ...item, enabled } : item))} /><Input aria-label="Folder name" placeholder="Folder name" value={rule.folder} onChange={(event) => persistRules(rules.map((item) => item.id === rule.id ? { ...item, folder: event.target.value } : item))} /><Input aria-label="Host contains" placeholder="Host, e.g. github.com" value={rule.host ?? ''} onChange={(event) => persistRules(rules.map((item) => item.id === rule.id ? { ...item, host: event.target.value || null } : item))} /><Input aria-label="Path prefix" placeholder="Path prefix (optional)" value={rule.pathPrefix ?? ''} onChange={(event) => persistRules(rules.map((item) => item.id === rule.id ? { ...item, pathPrefix: event.target.value || null } : item))} /><Input aria-label="Title contains" placeholder="Title contains (optional)" value={rule.titleContains ?? ''} onChange={(event) => persistRules(rules.map((item) => item.id === rule.id ? { ...item, titleContains: event.target.value || null } : item))} /><Button size="icon" variant="ghost" aria-label="Delete rule" onClick={() => persistRules(rules.filter((item) => item.id !== rule.id))}><AppIcon name="Trash2" /></Button></div>)}</section>
      </>}
      {section === 'Appearance' && <>
        <section className="page-section"><h2>Theme</h2><div className="theme-grid">{themes.map((theme) => <button className="theme-card" key={theme.id} data-selected={String(settings.theme === theme.id)} onClick={() => { document.documentElement.dataset.themeDark = String(theme.dark); patch({ theme: theme.id }); void api.setTheme(theme.id) }}><span className="theme-preview" data-part="theme-preview" style={{ '--preview-bg': theme.dark ? 'var(--sidebar)' : 'var(--card)' } as React.CSSProperties} /><strong>{theme.name}</strong><span className="muted-copy">{theme.dark ? 'Dark' : 'Light'} · {theme.source}</span></button>)}</div></section>
        <section className="page-section"><h2>Density</h2><div className="segmented"><button data-active={String(localStorage.getItem('athanor-density') !== 'compact')} onClick={() => setDensity('comfortable')}>Comfortable</button><button data-active={String(localStorage.getItem('athanor-density') === 'compact')} onClick={() => setDensity('compact')}>Compact</button></div><p>Choose the amount of space between tab rows and controls.</p></section>
      </>}
      {section === 'Extensions' && <section className="page-section"><div className="list-heading"><div><h2>Installed extensions</h2><p>Panels and commands run in a restricted extension frame.</p></div><Button onClick={() => void install()}><AppIcon name="Plus" />Install from directory</Button></div>{extensions.length === 0 && <p className="muted-copy">No extensions installed.</p>}{extensions.map((extension) => <ExtensionRow key={extension.id} extension={extension} onRefresh={() => void api.listExtensions().then(setExtensions)} />)}</section>}
      {section === 'Shortcuts' && <section className="page-section"><h2>Keyboard shortcuts</h2><div className="shortcuts-list">{shortcuts.map(([label, key]) => <div key={key} className="shortcut-row"><span>{label}</span><kbd>{key}</kbd></div>)}</div></section>}
      {section === 'About' && <section className="page-section about-card"><span className="brand-mark"><AppIcon name="WandSparkles" /></span><h2>Athanor</h2><p>Version {snapshot?.version ?? '—'}</p><p>A lightweight browser shell made for focus, research, and developer work.</p><div className="about-facts"><span>Platform <strong>{snapshot?.platform}</strong></span><span>Spaces <strong>{snapshot?.workspace.spaces.length}</strong></span><span>Open tabs <strong>{snapshot?.workspace.tabs.length}</strong></span></div></section>}
    </div>
  </div>
}

function MyFiltersEditor() {
  const [text, setText] = useState('')
  const [saved, setSaved] = useState('')
  const [issues, setIssues] = useState<LineIssue[]>([])
  const [saving, setSaving] = useState(false)
  const area = useRef<HTMLTextAreaElement>(null)
  useEffect(() => { let alive = true; void api.getUserFilters().then((value) => { if (alive) { setText(value); setSaved(value) } }).catch(() => toast.error('Filters could not be loaded.')); return () => { alive = false } }, [])
  const dirty = text !== saved
  const save = async () => {
    if (!dirty || saving) return
    setSaving(true)
    try { const found = await api.setUserFilters(text); setSaved(text); setIssues(found); toast.success(found.length ? `Filters saved · ${ignoredLineSummary(found.length)}` : 'Filters saved') }
    catch (error) { toast.error(error instanceof Error ? error.message : String(error)) }
    finally { setSaving(false) }
  }
  const jump = (line: number) => { const node = area.current; if (!node) return; const range = lineSelectionRange(text, line); node.focus(); node.setSelectionRange(range.start, range.end) }
  const lines = countFilterLines(text)
  return <>
    <p className="filter-help" id="my-filters-help">One rule per line, for example <code>||ads.example.com^</code>, <code>example.com##.banner</code>, <code>@@||example.com^$document</code>.</p>
    <textarea ref={area} id="my-filters" data-part="my-filters" className="textarea" aria-label="My filters" aria-describedby="my-filters-help" rows={12} wrap="off" spellCheck={false} value={text} placeholder="||ads.example.com^" onChange={(event) => setText(event.target.value)} onKeyDown={(event) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 's') { event.preventDefault(); void save() } }} />
    <div className="filter-actions"><Button onClick={() => void save()} disabled={!dirty || saving}><AppIcon name="Check" />{saving ? 'Saving…' : 'Save'}</Button><Button variant="outline" onClick={() => setText(saved)} disabled={!dirty || saving}><AppIcon name="RotateCcw" />Revert</Button><span className="filter-count"><span className="muted-copy" data-part="filter-count">{lineCountLabel(lines)}</span><span className="filter-hint"><span className="muted-copy">·</span><kbd>Ctrl</kbd><kbd>S</kbd></span></span></div>
    {issues.length > 0 && <><p className="filter-report muted-copy">The engine ignored {lineCountLabel(issues.length)}:</p><ul className="filter-issues" data-part="filter-issues" aria-label="Ignored lines">{issues.map((issue) => <li key={`${issue.line}-${issue.message}`}><button type="button" className="filter-issue" data-part="filter-issue" aria-label={issue.line ? `Select line ${issue.line}` : 'Select all filters'} onClick={() => jump(issue.line)}><AppIcon name="XCircle" /><span><strong>{issue.line ? `Line ${issue.line}:` : 'All lines:'}</strong> <span className="muted-copy">{issue.message}</span></span></button></li>)}</ul></>}
  </>
}
function SwitchRow({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (value: boolean) => void }) { return <div className="setting-row"><div><strong>{label}</strong><span className="muted-copy">{description}</span></div><Switch checked={checked} label={label} onChange={onChange} /></div> }
function Switch({ checked, label, onChange }: { checked: boolean; label: string; onChange: (value: boolean) => void }) { return <button className="switch" data-checked={String(checked)} role="switch" aria-label={label} aria-checked={checked} onClick={() => onChange(!checked)} /> }
function ExtensionRow({ extension, onRefresh }: { extension: ExtensionInfo; onRefresh: () => void }) { return <div className="extension-row"><div className="extension-info"><span className="speed-icon"><AppIcon name="Zap" /></span><div><strong>{extension.name}</strong><span className="muted-copy">{extension.description}</span><span className="muted-copy">Permissions: {extension.permissions.join(', ') || 'None'} · {extension.version}</span></div></div><div className="extension-actions"><Switch checked={extension.enabled} label={`${extension.name} enabled`} onChange={(enabled) => void api.setExtensionEnabled(extension.id, enabled).then(onRefresh)} />{extension.source === 'user' && <Button variant="ghost" size="icon" aria-label={`Remove ${extension.name}`} onClick={() => void api.removeExtension(extension.id).then(onRefresh)}><AppIcon name="Trash2" /></Button>}</div></div> }
function setDensity(value: 'compact' | 'comfortable') { localStorage.setItem('athanor-density', value); window.dispatchEvent(new CustomEvent('athanor-density', { detail: value })) }
