import { invoke } from '@tauri-apps/api/core'
import type { Board, CommandArgs, CommandResult, DevTool, FilingRule, Id, Settings, SplitArgs } from './types'
import { mockInvoke, isMockMode } from './mock/backend'

async function call<K extends keyof CommandArgs>(name: K, args: CommandArgs[K]): Promise<K extends keyof CommandResult ? CommandResult[K] : void> {
  const result = isMockMode() ? await mockInvoke(name, args) : await invoke(name, args as unknown as Record<string, unknown>)
  return result as K extends keyof CommandResult ? CommandResult[K] : void
}

export const api = {
  pageMedia: (tab: Id, action: 'state' | 'toggle-play' = 'state') => call('page_media', { tab, action }),
  passwordList: () => call('password_list', {}), passwordImport: () => call('password_import', {}), passwordRemove: (id: string) => call('password_remove', { id }), passwordFill: (id: string, tab: Id) => call('password_fill', { id, tab }),
  getDownloads: () => call('get_downloads', {}), controlDownload: (id: number, action: 'pause' | 'resume' | 'cancel') => call('control_download', { id, action }),
  getSnapshot: () => call('get_snapshot', {}), getShellCss: () => call('get_shell_css', {}),
  listThemes: () => call('list_themes', {}), setTheme: (id: string) => call('set_theme', { id }), setSpaceTheme: (space: Id, theme: string | null) => call('set_space_theme', { space, theme }),
  getPanels: () => call('get_panels', {}), getCommands: () => call('get_commands', {}), runExtensionCommand: (ext: string, id: string) => call('run_extension_command', { ext, id }), extensionRpc: (ext: string, method: string, params: unknown) => call('extension_rpc', { ext, method, params }),
  openTab: (args: CommandArgs['open_tab'] = {}) => call('open_tab', args), navigate: (tab: Id, input: string) => call('navigate', { tab, input }), activateTab: (tab: Id) => call('activate_tab', { tab }), closeTab: (tab: Id) => call('close_tab', { tab }), duplicateTab: (tab: Id) => call('duplicate_tab', { tab }), reload: (tab: Id) => call('reload', { tab }), stop: (tab: Id) => call('stop', { tab }), goBack: (tab: Id) => call('go_back', { tab }), goForward: (tab: Id) => call('go_forward', { tab }), setPinned: (tab: Id, pinned: boolean) => call('set_pinned', { tab, pinned }), setMuted: (tab: Id, muted: boolean) => call('set_muted', { tab, muted }), moveTab: (args: CommandArgs['move_tab']) => call('move_tab', args), closeOtherTabs: (tab: Id) => call('close_other_tabs', { tab }), closeTabsBelow: (tab: Id) => call('close_tabs_below', { tab }), restoreTab: (tab: Id) => call('restore_tab', { tab }), copyUrl: (tab: Id) => call('copy_url', { tab }),
  createFolder: (space: Id, name: string) => call('create_folder', { space, name }), renameFolder: (id: Id, name: string) => call('rename_folder', { id, name }), toggleFolder: (id: Id) => call('toggle_folder', { id }), deleteFolder: (id: Id, closeTabs: boolean) => call('delete_folder', { id, closeTabs }), setFolderColor: (id: Id, color: string | null) => call('set_folder_color', { id, color }),
  addSpace: (name: string, icon: string, color: string) => call('add_space', { name, icon, color }), renameSpace: (id: Id, name: string) => call('rename_space', { id, name }), removeSpace: (id: Id) => call('remove_space', { id }), switchSpace: (id: Id) => call('switch_space', { id }), updateSpace: (id: Id, patch: { icon?: string; color?: string }) => call('update_space', { id, ...patch }),
  autoFileAll: () => call('auto_file_all', {}), undoFileAll: (undo: number) => call('undo_file_all', { undo }), setFilingRules: (rules: FilingRule[]) => call('set_filing_rules', { rules }), archiveInactiveNow: () => call('archive_inactive_now', {}),
  splitWith: (args: SplitArgs) => call('split_with', args), unsplit: () => call('unsplit', {}), setSplitRatio: (path: boolean[], ratio: number) => call('set_split_ratio', { path, ratio }), focusPane: (tab: Id) => call('focus_pane', { tab }), getSplitRects: () => call('get_split_rects', {}),
  checkUpdate: () => call('check_update', {}), downloadUpdate: () => call('download_update', {}), installUpdate: () => call('install_update', {}),
  resolveScriptDialog: (tab: Id, accept: boolean, text: string) => call('resolve_script_dialog', { tab, accept, text }), resolvePermission: (tab: Id, id: number, allow: boolean, remember: boolean, origin: string, kind: string) => call('resolve_permission', { tab, id, allow, remember, origin, kind }), resetSitePermissions: () => call('reset_site_permissions', {}), revealDownload: (path: string) => call('reveal_download', { path }),
  reopenClosed: (count: number) => call('reopen_closed', { count }),
  setSoftwareRendering: (tab: Id, software: boolean) => call('set_software_rendering', { tab, software }),
  zoomPage: (tab: Id, dir: number) => call('zoom_page', { tab, dir }), findInPage: (tab: Id, action: 'start' | 'next' | 'prev' | 'clear', query: string, matchCase: boolean) => call('find_in_page', { tab, action, query, matchCase }), hardReload: (tab: Id) => call('hard_reload', { tab }), printPage: (tab: Id) => call('print_page', { tab }), toggleFullscreen: () => call('toggle_fullscreen', {}), focusShell: () => call('focus_shell', {}), focusPage: (tab: Id) => call('focus_page', { tab }), runShortcut: (combo: string) => call('run_shortcut', { combo }),
  translatePage: (tab: Id, lang: string) => call('translate_page', { tab, lang }),
  navHistory: (tab: Id) => call('nav_history', { tab }), navHistoryGo: (tab: Id, entry: number) => call('nav_history_go', { tab, entry }),
  boardPickPureref: () => call('board_pick_pureref', {}), boardImportPureref: (path: string) => call('board_import_pureref', { path }),
  windowGetPosition: () => call('window_get_position', {}), windowMoveTo: (x: number, y: number) => call('window_move_to', { x, y }),
  setContentBounds: (bounds: { x: number; y: number; w: number; h: number }) => call('set_content_bounds', bounds), setOverlayOpen: (open: boolean) => call('set_overlay_open', { open }), setPageRadius: (radius: number) => call('set_page_radius', { radius }), importDetect: () => call('import_detect', {}), importRun: (request: CommandArgs['import_run']['request']) => call('import_run', { request }), importPickFile: () => call('import_pick_file', {}), captureFrame: (tab: Id) => call('capture_frame', { tab }), resolveContextMenu: (tab: Id, command: number | null) => call('resolve_context_menu', { tab, command }), contextAction: (action: string, data: string) => call('context_action', { action, data }), setViewportEmulation: (tab: Id, preset: 'mobile' | 'tablet' | 'laptop' | null) => call('set_viewport_emulation', { tab, preset }),
  omniboxSuggest: (query: string) => call('omnibox_suggest', { query }), openDevtools: (tab: Id) => call('open_devtools', { tab }), runDevTool: (tool: DevTool, input: string) => call('run_dev_tool', { tool, input }), listDevServers: () => call('list_dev_servers', {}),
  listBoards: () => call('list_boards', {}), getBoard: (id: Id) => call('get_board', { id }), createBoard: (name: string) => call('create_board', { name }), saveBoard: (board: Board) => call('save_board', { board }), deleteBoard: (id: Id) => call('delete_board', { id }), boardPutAsset: (dataBase64: string, mime: string) => call('board_put_asset', { dataBase64, mime }), boardAddFromUrl: (id: Id, url: string, cx: number, cy: number) => call('board_add_from_url', { id, url, cx, cy }), openBoardWindow: (id: Id) => call('open_board_window', { id }), setBoardAlwaysOnTop: (id: Id, on: boolean) => call('set_board_always_on_top', { id, on }), sendPageImageToBoard: (tab: Id, boardId: Id) => call('send_page_image_to_board', { tab, boardId }),
  getAdblockStatus: () => call('get_adblock_status', {}), setAdblockEnabled: (enabled: boolean) => call('set_adblock_enabled', { enabled }), setAdblockListEnabled: (id: string, enabled: boolean) => call('set_adblock_list_enabled', { id, enabled }), updateAdblockLists: () => call('update_adblock_lists', {}), getSiteShield: (host: string) => call('get_site_shield', { host }), setSiteShield: (host: string, enabled: boolean) => call('set_site_shield', { host, enabled }),
  getUserFilters: () => call('get_user_filters', {}), setUserFilters: (text: string) => call('set_user_filters', { text }),
  getSettings: () => call('get_settings', {}), setSettings: (patch: Partial<Settings>) => call('set_settings', { patch }), listExtensions: () => call('list_extensions', {}), setExtensionEnabled: (id: string, enabled: boolean) => call('set_extension_enabled', { id, enabled }), installExtension: (path: string) => call('install_extension', { path }), removeExtension: (id: string) => call('remove_extension', { id }), pickDirectory: () => call('pick_directory', {}),
  windowMinimize: () => call('window_minimize', {}), windowToggleMaximize: () => call('window_toggle_maximize', {}), windowClose: () => call('window_close', {}), windowStartDrag: () => call('window_start_drag', {}), windowIsMaximized: () => call('window_is_maximized', {}),
}

export type Api = typeof api
